# render.yaml
services:
  - type: web
    name: news-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn news_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: news_project.settings
